#!/usr/bin/env bash
#Displays "To infinity and beyond" an infinite number of times
#Also displays "I am invincible!!!" when it receives a SIGTERM signal

trap "echo 'I am invincible!!!'" 15

while  true; do
	echo "To infinity and beyond"
	sleep 2
done
